spring:
  datasource:
    url: jdbc:h2:mem:database
    username: dev
    password: dev
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  main:
    banner-mode: off

  application:
    name: "messenger"

server:
  port: 8081